# -*- coding: utf-8 -*-
"""Matriz Gauss.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wpoqZpVGvtQwwxtVrMSssX_PC79BVnYP
"""

import numpy as np
A=np.array([[2,4,6,18,], [4,5,6,24], [3,1,-2,4]])
print(A)

print (A[1,3])

print (A[0,1])

A[0,]=(1/A[0,0])*A[0]

A[0,]=(1/A[0,0])*A[0]
print(A)

A[1,]=-A[1,0]*A[0,]+A[1,]
print(A)

A[2,]=-A[2,0]*A[0,]+A[2,]
print(A)

A[1,]=(1/A[1,1])*A[1,]
print(A)

A[0,]=-A[0,1]*A[1,]+A[0,]
print(A)

A[2,]=-A[2,1]*A[1,]+A[2,]
print(A)

A[2,]=(1/A[2,2]*A[2,])
print(A)

A[0,]=-A[0,2]*A[2,]+A[0,]
print(A)

A[1,]=-A[1,2]*A[2,]+A[1,]
print(A)

sol= np.array([A[0,3], A[1,3], A[2,3]])
print("La solucion es (x1,x2,x3)="); print(sol)

